In [7]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4, 5])
print('x = ', x , type(x))

x =  [1 2 3 4 5] <class 'numpy.ndarray'>


In [3]:
x.dtype

dtype('int32')

In [4]:
x.shape

(5,)

In [5]:
y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])
print(y)
y.shape

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


(4, 3)

In [6]:
y.size

12

In [9]:
!conda list pandas

# packages in environment at C:\Users\UN\anaconda3:
#
# Name                    Version                   Build  Channel
pandas                    1.1.3            py38ha925a31_0  


In [4]:
'message message'.capitalize()

'Message message'

In [5]:
'message message'.title()

'Message Message'

<a href=https://www.islamweb.net>jhkjhnkj</a> www.link.com

# Header 1

[Udacity's home page](https://www.udacity.com)

gelato
_gelato_
or *gelato*
**gelato**

`string.punctuation`
```
message='Hello!'
print(message)

```

```
import requests
response = requests.get('https://www.udacity.com')
```

$y = mx + b$

$$
y = \frac{a}{b+c}
$$

## Header 2

#### Header 4

In [8]:
%matplotlib

Using matplotlib backend: Qt5Agg


In [18]:
import numpy as np
np.linspace(0,5,25)

array([0.        , 0.20833333, 0.41666667, 0.625     , 0.83333333,
       1.04166667, 1.25      , 1.45833333, 1.66666667, 1.875     ,
       2.08333333, 2.29166667, 2.5       , 2.70833333, 2.91666667,
       3.125     , 3.33333333, 3.54166667, 3.75      , 3.95833333,
       4.16666667, 4.375     , 4.58333333, 4.79166667, 5.        ])

In [5]:
%pdb

Automatic pdb calling has been turned ON


In [6]:
numbers='hello'
sum(numbers)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

> <ipython-input-6-73ffa48bc494>(2)<module>()
      1 numbers='hello'
----> 2 sum(numbers)

ipdb> jnj
*** NameError: name 'jnj' is not defined
ipdb> numbers
'hello'
ipdb> q
